# Generated by Django 4.0.2 on 2022-02-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_blogmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='author',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default='', upload_to='blogimg/'),
            preserve_default=False,
        ),
    ]
